from client_detail import ClientDetail
from client_list import ClientList
from client_location_detail import ClientLocationDetail
from client_location_detail_detail import ClientLocationDetailDetail
from client_location_list import ClientLocationList
from client_location_meal_detail import ClientLocationMealDetail
from client_location_meal_list import ClientLocationMealList
from client_location_search_list import ClientLocationSearchList