from user_admin import UserAdmin
from user_location_admin import UserLocationAdmin
from user_meal_purchase_history_admin import UserMealPurchaseHistoryAdmin
from user_payment_info_admin import UserPaymentInfoAdmin
