from anonymous_user_admin import AnonymousUserAdmin
from anonymous_user_meal_purchase_history_admin import AnonymousUserMealPurchaseHistoryAdmin
from anonymous_user_payment_info_admin import AnonymousUserPaymentInfoAdmin
