from client_detail import ClientDetail
from client_location_list import ClientLocationList
from client_location_detail import ClientLocationDetail
from client_location_detail_detail import ClientLocationDetailDetail
