'GET /locations':               ['locations']
'GET /locations/:id':           ['locationsId']
'GET /locations/:id/meals':     ['locationsIdMeals']
'GET /locations/:id/drops':     ['locationsIdDrops']
'GET /meals':                   ['meals']
'GET /meals/:id':               ['mealsId']
'GET /users':                   ['users']
'GET /users/:id':               ['usersId']
'GET /addresses':               ['addresses']
'GET /addresses/:id':           ['addressesId']
